// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protobuf/climber.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetClimberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClimberRequest) Reset() {
	*x = GetClimberRequest{}
	mi := &file_protobuf_climber_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClimberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClimberRequest) ProtoMessage() {}

func (x *GetClimberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_climber_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClimberRequest.ProtoReflect.Descriptor instead.
func (*GetClimberRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_climber_proto_rawDescGZIP(), []int{0}
}

func (x *GetClimberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetClimberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClimberResponse) Reset() {
	*x = GetClimberResponse{}
	mi := &file_protobuf_climber_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClimberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClimberResponse) ProtoMessage() {}

func (x *GetClimberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_climber_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClimberResponse.ProtoReflect.Descriptor instead.
func (*GetClimberResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_climber_proto_rawDescGZIP(), []int{1}
}

func (x *GetClimberResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_protobuf_climber_proto protoreflect.FileDescriptor

const file_protobuf_climber_proto_rawDesc = "" +
	"\n" +
	"\x16protobuf/climber.proto\"'\n" +
	"\x11GetClimberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12GetClimberResponse\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info2F\n" +
	"\vClimberInfo\x127\n" +
	"\n" +
	"GetClimber\x12\x12.GetClimberRequest\x1a\x13.GetClimberResponse\"\x00B\x16Z\x14climberinfo/protobufb\x06proto3"

var (
	file_protobuf_climber_proto_rawDescOnce sync.Once
	file_protobuf_climber_proto_rawDescData []byte
)

func file_protobuf_climber_proto_rawDescGZIP() []byte {
	file_protobuf_climber_proto_rawDescOnce.Do(func() {
		file_protobuf_climber_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_climber_proto_rawDesc), len(file_protobuf_climber_proto_rawDesc)))
	})
	return file_protobuf_climber_proto_rawDescData
}

var file_protobuf_climber_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_climber_proto_goTypes = []any{
	(*GetClimberRequest)(nil),  // 0: GetClimberRequest
	(*GetClimberResponse)(nil), // 1: GetClimberResponse
}
var file_protobuf_climber_proto_depIdxs = []int32{
	0, // 0: ClimberInfo.GetClimber:input_type -> GetClimberRequest
	1, // 1: ClimberInfo.GetClimber:output_type -> GetClimberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_climber_proto_init() }
func file_protobuf_climber_proto_init() {
	if File_protobuf_climber_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_climber_proto_rawDesc), len(file_protobuf_climber_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_climber_proto_goTypes,
		DependencyIndexes: file_protobuf_climber_proto_depIdxs,
		MessageInfos:      file_protobuf_climber_proto_msgTypes,
	}.Build()
	File_protobuf_climber_proto = out.File
	file_protobuf_climber_proto_goTypes = nil
	file_protobuf_climber_proto_depIdxs = nil
}
