// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: protobuf/climber.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClimberInfo_GetClimber_FullMethodName = "/ClimberInfo/GetClimber"
)

// ClimberInfoClient is the client API for ClimberInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClimberInfoClient interface {
	GetClimber(ctx context.Context, in *GetClimberRequest, opts ...grpc.CallOption) (*GetClimberResponse, error)
}

type climberInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewClimberInfoClient(cc grpc.ClientConnInterface) ClimberInfoClient {
	return &climberInfoClient{cc}
}

func (c *climberInfoClient) GetClimber(ctx context.Context, in *GetClimberRequest, opts ...grpc.CallOption) (*GetClimberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClimberResponse)
	err := c.cc.Invoke(ctx, ClimberInfo_GetClimber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClimberInfoServer is the server API for ClimberInfo service.
// All implementations must embed UnimplementedClimberInfoServer
// for forward compatibility.
type ClimberInfoServer interface {
	GetClimber(context.Context, *GetClimberRequest) (*GetClimberResponse, error)
	mustEmbedUnimplementedClimberInfoServer()
}

// UnimplementedClimberInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClimberInfoServer struct{}

func (UnimplementedClimberInfoServer) GetClimber(context.Context, *GetClimberRequest) (*GetClimberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClimber not implemented")
}
func (UnimplementedClimberInfoServer) mustEmbedUnimplementedClimberInfoServer() {}
func (UnimplementedClimberInfoServer) testEmbeddedByValue()                     {}

// UnsafeClimberInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClimberInfoServer will
// result in compilation errors.
type UnsafeClimberInfoServer interface {
	mustEmbedUnimplementedClimberInfoServer()
}

func RegisterClimberInfoServer(s grpc.ServiceRegistrar, srv ClimberInfoServer) {
	// If the following call panics, it indicates UnimplementedClimberInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClimberInfo_ServiceDesc, srv)
}

func _ClimberInfo_GetClimber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClimberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClimberInfoServer).GetClimber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClimberInfo_GetClimber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClimberInfoServer).GetClimber(ctx, req.(*GetClimberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClimberInfo_ServiceDesc is the grpc.ServiceDesc for ClimberInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClimberInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClimberInfo",
	HandlerType: (*ClimberInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClimber",
			Handler:    _ClimberInfo_GetClimber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/climber.proto",
}
